

server:
  port: 7002
eureka:
  instance:
    hostname: localhost
    statuspageUrl: http://localhost:7002/index
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: pmit-system-manager


